spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/gestionDesEspaceVert
    username: postgres
    password: Cid*2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        proc:
          param_null_passing: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: achrafaouad7@gmail.com
    password: amrvaquhnwckspnc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
